### ISSUE TITLE
How can we make GovFresh better?

### ISSUE THREAD

**Issue by CenterForGovernmentInteroperability** [govfresh/feedback#1]
Feedback: Honestly, it is already an amazingly clear articulator of government improvement ideas.  Cannot think of any ways to make GovFresh better. There is a skilled ability for identifying innovation news and offering great ideas.

Alex Glaros

**Comment by lukefretwell** [comment]
Thank you @CenterForGovernmentInteroperability!

**Comment by vanschaik79** [comment]
Fabulous site. As a federal employee, I share articles often and use many to train my colleagues. The "Stay fresh" subscribe prompt, however, pops up too frequently. Plus, I already subscribe, yet I have to close the window 3-5 times every time I visit www.govfresh.com.

**Comment by lukefretwell** [comment]
Thank you @vanschaik79. I changed the settings so that it shows only once per day. Please let me know if it continues to be a nuisance.

**Comment by vanschaik79** [comment]
CLASSIFICATION: UNCLASSIFIED

 

You guys are incredible. Keep up the great work!

 

V/R,

 

Nathan Van Schaik

Public Affairs

U.S. Army Garrison Bavaria

DSN 475-6876, CIV 09641-83-6876

nathaniel.t.vanschaik.civ@mail.mil

Visit and follow us at:

 <http://www.bavaria.army.mil> www.bavaria.army.mil
